name: Python package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] #, 'macos-latest'] #, 'windows-latest']
        python-version: ['3.11'] # '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Install EPANET quantum and set environment variables
        run: |
          git clone https://github.com/QuantumApplicationLab/EPANET
          echo "EPANET_TMP=$RUNNER_TEMP" >> $GITHUB_ENV
          echo "EPANET_QUANTUM=${{ github.workspace }}/EPANET" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
      - name: Run unit tests
        run: python -m pytest -v
      - name: Verify that we can build the package
        run: python -m build

  lint:
    name: Linting build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Check style against standards using ruff
        run: ruff .
