name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Upgrade pip and install dependencies
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Install tox
        run: |
          pip install tox coveragepy-lcov 'coverage<7'
      - name: Install EPANET quantum and set environment variables
        run: |
          git clone https://github.com/QuantumApplicationLab/EPANET
          echo "EPANET_TMP=$RUNNER_TEMP" >> $GITHUB_ENV
          echo "EPANET_QUANTUM=${{ github.workspace }}/EPANET" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
      - name: Run coverage
        run: |
          coverage3 run --source wntr_quantum --parallel-mode -m pytest --doctest-modules
          coverage3 combine
          coverage3 report      
      - name: Convert to lcov
        run: coveragepy-lcov --output_file_path coveralls.info
      - name: Upload report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coveralls.info
          format: lcov
